//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;



[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name="udsTransOutput", Namespace="http://schemas.datacontract.org/2004/07/")]
public partial class udsTransOutput : object, System.Runtime.Serialization.IExtensibleDataObject
{
    
    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
    
    private bool blnSuccessField;
    
    private int intExceptionField;
    
    private string strDataField;
    
    private string strExceptionField;
    
    private string strVersionField;
    
    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
        get
        {
            return this.extensionDataField;
        }
        set
        {
            this.extensionDataField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public bool blnSuccess
    {
        get
        {
            return this.blnSuccessField;
        }
        set
        {
            this.blnSuccessField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int intException
    {
        get
        {
            return this.intExceptionField;
        }
        set
        {
            this.intExceptionField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string strData
    {
        get
        {
            return this.strDataField;
        }
        set
        {
            this.strDataField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string strException
    {
        get
        {
            return this.strExceptionField;
        }
        set
        {
            this.strExceptionField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string strVersion
    {
        get
        {
            return this.strVersionField;
        }
        set
        {
            this.strVersionField = value;
        }
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ITrans")]
public interface ITrans
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrans/objExecute", ReplyAction="http://tempuri.org/ITrans/objExecuteResponse")]
    udsTransOutput objExecute(
                string strAppCode, 
                string strVenueCode, 
                string strCommand, 
                string strParam1, 
                string strParam2, 
                string strParam3, 
                string strParam4, 
                string strParam5, 
                string strParam6, 
                string strParam7, 
                string strParam8, 
                string strParam9, 
                string strParam10, 
                string strParam11, 
                string strParam12, 
                string strParam13, 
                string strParam14, 
                string strParam15);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ITransChannel : ITrans, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class TransClient : System.ServiceModel.ClientBase<ITrans>, ITrans
{
    
    public TransClient()
    {
    }
    
    public TransClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public TransClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public TransClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public TransClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public udsTransOutput objExecute(
                string strAppCode, 
                string strVenueCode, 
                string strCommand, 
                string strParam1, 
                string strParam2, 
                string strParam3, 
                string strParam4, 
                string strParam5, 
                string strParam6, 
                string strParam7, 
                string strParam8, 
                string strParam9, 
                string strParam10, 
                string strParam11, 
                string strParam12, 
                string strParam13, 
                string strParam14, 
                string strParam15)
    {
        return base.Channel.objExecute(strAppCode, strVenueCode, strCommand, strParam1, strParam2, strParam3, strParam4, strParam5, strParam6, strParam7, strParam8, strParam9, strParam10, strParam11, strParam12, strParam13, strParam14, strParam15);
    }
}
